name: "FuseDrill"
description: "Automatic fuzzing/simulation testing for OpenAPIs"
author: "Martynas Pocius"
branding:
  icon: "zap"
  color: "green"

inputs:
  fuseDrillBaseAddres:
    description: "Base address of the FuseDrill API"
    required: true
    type: string
  fuseDrillOpenApiUrl:
    description: "OpenAPI URL for FuseDrill"
    required: true
    type: string
  fuseDrillTestAccountOAuthHeaderValue:
    description: "OAuth header value for test account"
    required: true
    type: string

permissions:
  contents: write  # Enables both read and write access to repository content

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore

    - name: Run FuseDrill CLI
      env:
        FUSEDRILL_BASE_ADDRESS: ${{ inputs.fuseDrillBaseAddres }}
        FUSEDRILL_OPENAPI_URL: ${{ inputs.fuseDrillOpenApiUrl }}
        FUSEDRILL_TEST_ACCOUNT_OAUTH_HEADER_VALUE: ${{ inputs.fuseDrillTestAccountOAuthHeaderValue }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: dotnet run --project src/FuseDrill.Cli/FuseDrill.Cli.csproj
