name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # Enables both read and write access to repository content
  actions: read    # Allows reading actions metadata (if needed)
  statuses: write  # Allows setting commit statuses (optional)

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Define the token once for all steps

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Print environment variables
      run: printenv
    - name: Run FuseDrill CLI
      run: dotnet run --project src/FuseDrill.Cli/FuseDrill.Cli.csproj
