name: Publish cli

on:
  release:
    types:
      - published

permissions:
  contents: write
  packages: write  # Allow pushing to GHCR
  id-token: write  # This is required for actions interacting with GitHub Packages

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Dotnet publish image
      run: dotnet publish /t:PublishContainer -c Release --runtime linux-x64

    - name: Dotnet test
      run: dotnet test

    - name: Tag image
      run: docker tag fusedrill-cli:latest ghcr.io/martasp/fusedrill/fusedrill-cli:latest

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Docker Image to GHCR
      run: docker push ghcr.io/martasp/fusedrill/fusedrill-cli:latest

    - name: Remove local Docker image
      run: docker rmi fusedrill-cli:latest

    - name: Pull FuseDrill Docker Image
      run: docker pull ghcr.io/martasp/fusedrill/fusedrill-cli:latest

    - name: Run FuseDrill CLI in Docker
      run: |
        docker run --rm \
          -e FUSEDRILL_BASE_ADDRESS="https://api.apis.guru/v2" \
          -e FUSEDRILL_OPENAPI_URL="https://api.apis.guru/v2/openapi.yaml" \
          -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
          -e SMOKE_FLAG="true" \
          -e GITHUB_REPOSITORY_OWNER="${{ github.repository_owner }}" \
          -e GITHUB_REPOSITORY="${{ github.repository }}" \
          -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
          ghcr.io/martasp/fusedrill/fusedrill-cli:latest

  # old way
    # - name: Build Single-File Executable
    #   run: dotnet publish src/FuseDrill.Cli/FuseDrill.Cli.csproj -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -o ./publish

    # - name: Verify Build Output
    #   run: ls -la ./publish

    # - name: Rename Executable
    #   run: mv ./publish/FuseDrill.Cli ./FuseDrill  # Rename to FuseDrill

    # - name: Upload Executable to GitHub Release
    #   uses: actions/upload-release-asset@v1
    #   with:
    #     upload_url: ${{ github.event.release.upload_url }}
    #     asset_path: ./FuseDrill
    #     asset_name: FuseDrill
    #     asset_content_type: application/octet-stream
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Build Docker Image (scratch)
    #   run: |
    #     # Build Dockerfile
    #     echo "FROM scratch" > Dockerfile
    #     echo "COPY FuseDrill /FuseDrill" >> Dockerfile  # Copy FuseDrill to the root of the container
    #     echo "ENTRYPOINT [\"/FuseDrill\"]" >> Dockerfile  # Set entrypoint to the executable
    #     echo "CMD []" >> Dockerfile  # No default arguments
    #     docker build -t ghcr.io/${{ github.repository_owner }}/fusedrill:latest .
