name: "FuseDrill Testing Workflow"
# description: "Automatic fuzzing/simulation testing for OpenAPIs using FuseDrill"

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write # Enables both read and write access to repository content

jobs:
  fuseDrill-test:
    runs-on: ubuntu-latest

    steps:

      - name: Start API with nohup
        run: |
          nohup dotnet run --project tests/TestApi/TestApi.csproj > api.log 2>&1 &
          echo $! > api_process_id.txt

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull FuseDrill Docker Image
        run: docker pull ghcr.io/martasp/fusedrill/fusedrill-cli:latest

      - name: Run FuseDrill CLI in Docker
        run: |
          docker run --rm \
            -e FUSEDRILL_BASE_ADDRESS="http://localhost:5184/" \
            -e FUSEDRILL_OPENAPI_URL="http://localhost:5184/swagger/v1/swagger.json" \
            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -e SMOKE_FLAG="true" \
            -e GITHUB_REPOSITORY_OWNER="${{ github.repository_owner }}" \
            -e GITHUB_REPOSITORY="${{ github.repository }}" \
            -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
            ghcr.io/martasp/fusedrill/fusedrill-cli:latest

            

          
